server:
  port: 8888

spring:
  # 집 로컬 DB
#  datasource:
#    url: jdbc:mysql://127.0.0.1:3306/local?useSSL=false&useUnicode=true&serverTimezone=Asia/Seoul
#    username: local
#    password: 1234

    # 회사 로컬 DB
  driver-class-name: org.mariadb.jdbc.Driver
  url: jdbc:mariadb://localhost:3306/zm
  username: zmgu
  password: 1234

#  jpa:
#    hibernate:
#      ddl-auto: create
#      naming:
#        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

  jwt:
    secret: vmfhaltmskdlstkfkdgodyroqkfwkdbalroqkfwkdbalaaaaaaaaaaaaaaaabbbbb

  security:
    oauth2:
      client:
        registration:
          google:
            client-name: google
            client-id: 533928876085-ft6922qekjofukqrarogpc1jptjnq6s1.apps.googleusercontent.com
            client-secret: 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
            redirect-uri: http://localhost:8888/login/oauth2/code/google
            authorization-grant-type: authorization_code
            scope: profile,email

          naver:
            client-name: naver
            client-id: NlqMTGSEmU7X82JoWpM7
            client-secret: 0berfgEzx3
            redirect-uri: http://localhost:8888/login/oauth2/code/naver
            authorization-grant-type: authorization_code
            scope: name,email

        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response